api/urls.py
from django.urls import path,include
from .  import views
from django.views.generic import TemplateView

app_name="api"

urlpatterns = [
    path('asset-info/',views.ApiView.as_view(),name="ApiView"),

]

auto_cmdb/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from extra_apps import xadmin
from auto_cmdb.settings import MEDIA_ROOT
from django.views.static import serve
from .views import DashView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('', TemplateView.as_view(template_name='index2.html'),name="index"),
    path('users/', include('users.urls')),
    path('cmdb/', include('cmdb.urls')),
    path('octoups/', include('octoups.urls'),name="octoups"),
    path('api/', include('api.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    path('dash/',DashView.as_view()),

    path('aa/',TemplateView.as_view(template_name="octoups/connection.html"))
]

octoups/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView


app_name = "octoups"

urlpatterns = [
    path("connection/",views.ConnectionView.as_view(),name="connection"),
    path("run/",views.ExecCommandView.as_view(),name="run"),
    path("get_result/",views.CommandResultView.as_view(),name="get_result"),
    path("async/",views.AsyncDemoView.as_view(),name="async"),
    path("ansible-adhoc",views.AnsibleAdhocView.as_view(),name="anisble-hoc")
]

octoups/models.py
from django.db import models

# Create your models here.

octoups/views.py
from celery.result import AsyncResult
from .utils.handlecommand import handlecommand
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.generic import View, ListView, DetailView


from cmdb.models import Server, Invertory_group, Invertory_group
import pexpect
import subprocess
import json
import os


class ConnectionView(View):
    def get(self, request):
        conninfo = Server.objects.all()

        return render(request, "octoups/connection.html", {"connection": conninfo})

    def post(self, request):
        id = request.POST.get("server_id")
        server = Server.objects.filter(id=id)[0]
        auth = server.connection.auth
        if auth:
            # 还需要判断推送的公钥和现有的公钥是否一致
            return JsonResponse({"status": "公钥不需要再次推送"})

        user = server.connection.user
        port = server.connection.port
        ip = server.manager_ip

        shell_command = "ssh-copy-id -p {} {}@{} ".format(port, user, ip)
        print(shell_command)

        child = pexpect.spawn(shell_command)

        index = child.expect(["yes/no", "password", "exist",
                              pexpect.exceptions.EOF, pexpect.TIMEOUT], timeout=5)
        try:
            print("开始向%s上传公钥" % (ip))
            child.sendline("yes")
            child.expect("password")
            child.sendline("qwe123qwe")
            child.expect("added")
            print("已向%s上传公钥" % (ip))
            server.connection.auth = True
            server.connection.save()
            return JsonResponse({"status": True})
        except Exception as e:
            return JsonResponse({"status": False})


class ExecCommandView(View):
    def get(self, request):
        
        invertory = Invertory_group.objects.all()
        return render(request, "octoups/run.html", {"data": invertory})

    def post(self, request):
        command = request.POST.get("data")

        from .tasks import exec_command

        task_id = exec_command.delay(command)
        return JsonResponse({"task_id": task_id.id})


class CommandResultView(View):
    def get(self, request):
        task_id = request.GET.get("task_id")
        task_obj = AsyncResult(id=task_id)
        task_json = {
            "id": task_obj.id,
            "status": task_obj.status,
            "success": task_obj.successful(),
            "result": task_obj.result
        }
        
        return JsonResponse(task_json)


class AsyncDemoView(View):
    def get(self, request):
        return render(request, "octoups/async-demo.html")

    def post(self, request):
        num = request.POST.get("num")
        from .tasks import add
        result = add.delay(int(num))
        print("命令已送达")
        return JsonResponse({"task_id": result.task_id})


class AnsibleAdhocView(View):
    def get(self, request):
        inventory = Invertory_group.objects.all()

        return render(request, "octoups/ansible-adhoc.html", {"info": inventory})

    def post(self, request):

        inv_path = request.POST.get("inv_path")
        remote_user = request.POST.get("remote_user")
        connection = request.POST.get("connection")
        model = request.POST.get("model")
        group = request.POST.get("group")
        args = request.POST.get("args")

        from octoups.tasks import ansible_ad_hoc

        result = ansible_ad_hoc.delay(connection, remote_user, inv_path, group, model, args)


        return JsonResponse({"task_id": result.task_id})

templates/octoups/ansible-adhoc.html
{% extends 'base.html' %}

{% block content %}
<div>
    {% csrf_token %}
    <div class="form-group has-warning">
        <label class="control-label" for="inputWarning"><i class="fa fa-bell-o"></i>主机清单文件路径</label>
        <input type="text" class="form-control" id="path" placeholder="输入文件路径"
            value="/home/alice/项目/jpx/auto_cmdb/auto_cmdb/octoups/inventory/hosts">
        <span class="help-block"></span>
    </div>
    <div class="form-group">
        <label>connection</label>
        <select class="form-control" id="connection">
            <option value="smart">smart</option>
            <option value="local">local</option>
        </select>
    </div>
    <div class="form-group">
        <label>remote_user</label>
        <select class="form-control" id="remote_user">
            <option value="root">root</option>
            <option value="stus">stus</option>
        </select>
    </div>
    <div class="form-group">
        <label>模块</label>
        <select class="form-control" id="model">
            <option value="shell">shell</option>
            <option value="ping">ping</option>
        </select>
    </div>
    <div class="form-group">
        <label>命令参数</label>
        <input type="text" class="form-control" id="args" placeholder=" 输入模块参数">
        <span class="help-block"></span>
    </div>
    <div class="form-group">
        <label>hosts</label>
        <select class="form-control" id="group">
            <option value="web-server">web-server</option>
            <option value="all" selected="selected">all</option>
            <option value="nginx">nginx</option>
        </select>
    </div>
    <button class="btn btn-success" id="btn" type="button">提交</button>
    <div>
        <span id="display_result"></span>
    </div>

</div>

{% endblock %}

{% block script %}
<script>
    var task_id = ''
    $(function () {
        function getresult(task_id) {
            var timer = setTimeout(function f(task_id) {
                $.getJSON(
                    url = `/octoups/get_result/?task_id=${task_id}`,
                    function (ret) {
                        console.log(ret)
                        if (ret.success) {
                            $("#display_result").append(`<div><code >${ret.id}</code><div>`)
                            $("#display_result").append(`<div><code >${ret.status}</code><div>`)
                            $("#display_result").append(
                            `<div><code >任务结果${ret.result}</code><div>`);
                            clearTimeout(timer);
                        } else {
                            $("#display_result").append(`<div><code >${ret.id}</code><div>`);
                            $("#display_result").append(`<div><code >${ret.status}</code><div>`);
                        };
                    }
                )
                timer = setTimeout(f, 2000, task_id);
            }, 2000, task_id);
        }

        $("#btn").on("click", function () {
            var inv_path = $("#path").val()
            var remote_user = $("#remote_user").val()
            var connection = $("#connection").val()
            var model = $("#model").val()
            var group = $("#group").val()
            var args = $("#args").val()


            $.ajax({
                url: "{% url 'octoups:anisble-hoc' %}",
                type: "POST",
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    "inv_path": inv_path,
                    "remote_user": remote_user,
                    "connection": connection,
                    "model": model,
                    "group": group,
                    "args": args
                },
                success: function (res) {
                    task_id = res.task_id
                    getresult(task_id)
                }
            })

        })


    })

</script>


{% endblock %}

templates/octoups/async-demo.html
{% extends 'base.html' %}

{% block content %}
内容
{% csrf_token %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <input type="text">
        <span>
            <button class="btn btn-success" id="btn">发送</button>
        </span>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <button type="button" class="btn btn-danger" id="get_result">获取结果</button>
        <div><span id="result"></span></div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    var task_id = ''
    $(function () {
        $("#btn").on("click", function () {
            var csrfToken = $("[name='csrfmiddlewaretoken']").val();
            let input = $(this).parent().siblings().first().val()
            console.log(input)
            $.ajax({
                url: "/octoups/async/",
                type: "POST",
                data: {
                    'csrfmiddlewaretoken': csrfToken,
                    "num": input
                },
                success(ret) {
                    task_id = ret.task_id
                }
            })
        })

        $("#get_result").on("click", function () {
            $.ajax({
                url: `/octoups/get_result/?task_id=${task_id}`,
                type: "GET",
                success(res) {
                    console.log(res)
                    $("#result").append(res.id)
                }
            })
        })
    })

</script>

{% endblock %}

templates/octoups/connection.html
{% extends 'base.html' %}
{% block content %}

<!-- 显示的字段 
        服务器的主机名  ip  用户名  密码  端口  是否认证-->
{%  csrf_token %}
<div class="col-xs-12">
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">用户公钥认证</h3>

            <div class="box-tools">
                <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>服务器主机名</th>
                        <th>ip</th>
                        <th>用户名</th>
                        <th>端口</th>
                        <th>是否认证</th>
                        <th>点击推送公钥</th>
                    </tr>
                    {% for server in connection %}
                    <tr>
                        <td>{{ server.id  }}</td>
                        <td>{{ server.host_name }}</td>
                        <td>{{ server.manager_ip }}</td>
                        <td>{{ server.connection.user }}</td>
                        <td>{{ server.connection.port }}</td>
                        {% if server.connection.auth %}
                        <td>
                            <span class="label label-success">{{ server.connection.auth }}</span>
                        </td>
                        {% else %}
                        <td>
                            <span class="label label-warning ">{{ server.connection.auth }}</span>
                        </td>
                        {% endif %}
                        <td><span class="label label-success pushPubKey ">点击推送公钥</span></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</div>
{% endblock %}

{% block script %}
<script>
    $(".pushPubKey").on("click", function () {
        let authed = '<span class="label label-success" > True </span>';
        let authedNot = '<span class="label label-danger"> False </span>';


        let id = $(this).parent().siblings().first().text()
        let statusTag = $(this).parent().siblings().last()
        var csrfToken = $("[name='csrfmiddlewaretoken']").val();

        $.ajax({
            url: "{% url 'octoups:connection' %}",
            type: "POST",
            data: {
                'csrfmiddlewaretoken': csrfToken,
                "server_id": id
            },
            success: function (res) {
                if (res.status) {
                    alert("免密连接成功")
                    statusTag.html(authed);
                } else {
                    alert("免密连接失败")
                }
            }
        })
    })

</script>
{% endblock %}

templates/octoups/run.html
{% extends 'base.html' %}

{% block title %}
<h1>操作指令</h1>
{% endblock %}


{% block content %}

<section class="content">
    <div class="row">
        <div class="col-md-3">
            <a href="#" class="btn btn-primary btn-block margin-bottom" id="RunCommand">提交</a>
            <!-- /. box -->
            {% for inventerory in data %}
            <div class="box box-solid">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ inventerory.group_name }}</h3>

                    <div class="box-tools">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body no-padding">
                    {% for server in inventerory.server.all %}
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#"><i class="fa fa-circle-o text-red"></i> {{ server.manager_ip }}</a></li>

                    </ul>
                    {% endfor %}

                </div>
                <!-- /.box-body -->
            </div>
            {% endfor %}
            <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">操作指令</h3>

                    <div class="box-tools pull-right">
                        <div class="has-feedback">
                            <input type="text" class="form-control input-sm" placeholder="Search Mail">
                            <span class="glyphicon glyphicon-search form-control-feedback"></span>
                        </div>
                    </div>
                    <!-- /.box-tools -->
                </div>
                <!-- /.box-header -->
                <div class="box-body no-padding">

                    <div class="table-responsive mailbox-messages input-group" style="padding: 10px">
                        <h3 style="display: inline-block">输入命令</h3>
                        <!-- <form action="{% url 'octoups:run' %}" method="POST"> -->
                        <!-- <form action="#" method="POST"> -->
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" name="message" id="command"
                                placeholder="ansible all -m shell -a 'ls /opt'" class="form-control"
                                style="width: 600px">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-warning btn-flat" id="pushcommand">Send</button>
                            </span>
                        </div>
                        <!-- </form> -->
                    </div>

                    <!-- /.mail-box-messages -->
                </div>
                <!-- /.box-body -->
                <div class="box-footer no-padding">

                </div>
            </div>
            <!-- /. box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9 col-sm-offset-3">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">操作指令</h3>

                    <div class="box-tools pull-right">
                        <div class="has-feedback">
                            <input type="text" class="form-control input-sm" placeholder="Search Mail">
                            <span class="glyphicon glyphicon-search form-control-feedback"></span>
                        </div>
                    </div>
                    <!-- /.box-tools -->
                </div>
                <!-- /.box-header -->
                <div class="box-body no-padding">

                    <div class="table-responsive mailbox-messages input-group" style="padding: 10px">
                        <span id="result_id"></span>
                        <button type="button" id="display_result">命令结果展示</button>
                    </div>

                    <!-- /.mail-box-messages -->
                </div>
                <!-- /.box-body -->
                <div class="box-footer no-padding">
                    <span id="result"></span>
                </div>
            </div>
            <!-- /. box -->
        </div>
    </div>
    <!-- /.row -->
</section>

{% endblock %}

{% block script %}
<script>
    $("#pushcommand").on("click", function () {
        let command = $("#command").val()
        var csrfToken = $("[name='csrfmiddlewaretoken']").val();
        console.log(command)
        $.ajax({
            url: "{% url 'octoups:run' %}",
            type: "POST",
            dataType: "json",
            data: {
                'csrfmiddlewaretoken': csrfToken,
                "data": command
            },
            success: function (res) {
                getresult(res.task_id)
            },
            error: function (res) {
                console.log(res)
            }
        })
    })

    function getresult(task_id) {
        var timer = setTimeout(function f(task_id) {
            $.getJSON(
                url = `/octoups/get_result/?task_id=${task_id}`,
                function (ret) {
                    if (ret.success) {
                        console.log(ret.result)
                        $("#result").append(`<div><code >${ret.id}</code><div>`)
                        $("#result").append(`<div><code >${ret.status}</code><div>`)
                        $("#result").append(`<div><code >任务结果${ret.result.result}</code><div>`);
                        clearTimeout(timer);
                    } else {
                        $("#result").append(`<div><code >${ret.id}</code><div>`);
                        $("#result").append(`<div><code >${ret.status}</code><div>`);
                    };
                }
            )
            timer = setTimeout(f, 2000, task_id);
        }, 2000, task_id);
    }

</script>
{% endblock %}